dia = input ('Qual é o seu dia de nascimento? ' )
mes = input ('Qual é o seu mês de nascimento? ' )
ano = input ('Qual é o seu ano de nascimento? ' )
print ('Você nasceu no dia:', dia, 'do mês:', mes, 'e do ano dê:', ano)
print('Forma resumida',dia,'/',mes,'/',ano)