delete from damat172_sistema.pacientes_exames where id > 0;
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479474', '1', '38', '53', '0', 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, '2019-02-15 13:45:34', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '24476', NULL, NULL, 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479475', '1', '38', '53', '0', '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, '2019-02-15 13:46:27', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '686799', NULL, NULL, '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479474', '1', '38', '53', '0', 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, '2019-02-15 13:45:34', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '24476', NULL, NULL, 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479475', '1', '38', '53', '0', '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, '2019-02-15 13:46:27', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '686799', NULL, NULL, '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479474', '1', '38', '53', '0', 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, '2019-02-15 13:45:34', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '24476', NULL, NULL, 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479475', '1', '38', '53', '0', '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, '2019-02-15 13:46:27', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '686799', NULL, NULL, '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479474', '1', '38', '53', '0', 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, '2019-02-15 13:45:34', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '24476', NULL, NULL, 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479475', '1', '38', '53', '0', '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, '2019-02-15 13:46:27', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '686799', NULL, NULL, '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479474', '1', '38', '53', '0', 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, '2019-02-15 13:45:34', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '24476', NULL, NULL, 'e4658fafd781f920cb1679efa4d437ae.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
insert into damat172_sistema.pacientes_exames(
	exame_id, paciente_id, motivo_id, cliente_id, medico_id, status, arquivo_exame, arquivo_laudo, create_date, observacoes, observacoes_medico, modelo_content, arquivos_selecionados, opcoes_impossibilitado, ativo, emergencia, laudo_impossibilitado, laudo_date, exame_date, medico_solicitante, sub_tipo_exame, peso, altura, imc, fumante, fumante_tempo, extra_data, preco_exame, preco_exame_medico, baixado, acuidade_perto_od, acuidade_perto_oe, acuidade_longe_od, acuidade_longe_oe, lente_corretiva, senso_cromatico, visao_noturna, visao_ofuscada, profundidade, crc, rnd, protocolo, arquivo_laudo_assinado, arquivo_imagem, arquivo_id, laudo_download_date, rx_digital, negatoscopio, qualidade, comentarios_qualidade, normal, anormalidade_parenquima, primarias, secundarias, zonas, profusao, grd_opacidade, anormalidade_pleural, placas_pleurais, placas_parede_local, placas_frontal_local, placas_diafrag_local, placas_outros_local, placas_parede_calcif, placas_frontal_calcif, placas_diafrag_calcif, placas_outros_calcif, placas_extensao_o_d, placas_extensao_o_e, placas_largura_d, placas_largura_e, obliteracao, espessamento_pleural, espes_parede_local, espes_frontal_local, espes_parede_calcif, espes_frontal_calcif, espes_extensao_o_d, espes_extensao_o_e, espes_largura_d, espes_largura_e, outras_anormalidades, simbolos, comentarios_laudo, reenviar_exame, enviado_por, empresa
) values (
	'1', '479475', '1', '38', '53', '0', '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, '2019-02-15 13:46:27', '', NULL, NULL, NULL, NULL, '1', '0', '0', NULL, '2019-02-15 00:00:00', '41', 'ECG', '82.00', '1.75', '26.78', NULL, NULL, NULL, '5.80', '3.00', NULL, '', '', '', '', NULL, NULL, NULL, NULL, NULL, convert(FLOOR(RAND() * 500), char(20)), '686799', NULL, NULL, '0adcb4961c03bab8a18c5cbc6a2a7ee0.jpeg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dama'
);
select * from damat172_sistema.pacientes_exames;
